baseURL = "https://andreasimonecosta.dev"
title = "andrea simone costa"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "dracula"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[params]
author = "Andrea Simone Costa"
description = "Andrea Simone Costa's personal website."
keywords = "blog,developer,personal,fp,javascript,typescript"
info = "Software Craftsman"
avatarURL = "images/avatar.jpg"
footerContent = "💻 Computer Scientist wannabe at @UniPisa, contravariant JS | TS developer."
dateFormat = "January 2, 2006"
hideFooter = false
hideCredits = true
hideCopyright = false
since = 1997
favicon_32 = "images/favicon.png"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Enable Twemoji
enableTwemoji = true
# Custom CSS
customCSS = []
# Custom SCSS
customSCSS = []
# Custom JS
customJS = ["js/svg.js"]

[[menu.main]]
name = "Blog"
weight = 1
url  = "posts/"

[[menu.main]]
name = "Courses"
weight = 1
url  = "/courses"

[[menu.main]]
name = "About Me"
weight = 1
url  = "/about-me"

[[params.social]]
name = "Github"
icon = "fa fa-github"
weight = 1
url = "https://github.com/jfet97"

[[params.social]]
name = "Twitter"
icon = "fa fa-twitter"
weight = 3
url = "https://twitter.com/JFieldEffectT"

[[params.social]]
name = "Telegram"
icon = "fa fa-telegram"
weight = 5
url = "https://t.me/jfet97"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/andrea-simone-costa/"

[[params.social]]
name = "YouTube"
icon = "fa fa-youtube"
weight = 4
url = "https://www.youtube.com/channel/UCKqAbvKIwqK_ZV2WS_6jitA/"


[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params.utterances]
  repo = "jfet97/blog-comments"
  issueTerm = "pathname"
  theme = "github-dark"
  enable = true
  label = "Comment"


[params.csp]
  childsrc = ["'self'"]
  fontsrc = [
    "'self'",
    "https://cdn.jsdelivr.net/"
  ]
  formaction = ["'self'"]
  framesrc = ["'self'"]
  imgsrc = ["'self'", "https://twemoji.maxcdn.com/", "https://jfet97.goatcounter.com/count"]
  objectsrc = ["'none'"]
  stylesrc = [
    "'self'",
    "'unsafe-inline'",
    "https://cdn.jsdelivr.net/",
  ]
  scriptsrc = [
    "'self'",
    "'unsafe-inline'",
    "https://twemoji.maxcdn.com/",
    "https://gc.zgo.at",
  ]
  prefetchsrc = ["'self'"]
  connectsrc = ["'self'"]


  [params.goatCounter]
  code = "jfet97"